name: Call CD workflow

on:
  workflow_dispatch:

jobs:
  call-cd-workflow:
    uses: bankwing/workflow-templates/.github/workflows/cd.yaml@main
    with:
      appname: ms-echo # set this to your application's name
      image-name: ${{ github.repository }}
      image-tag: ${{ github.sha }}
    secrets: inherit
