name: CI

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: node-echo    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
          languages: javascript
      
    - name: Download dependencies
      run: npm i 
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Download dependencies
      run: npm i 

    - name: Run Test
      run: npm run test

  sca:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Download dependencies
      run: npm i 

    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'node-echo'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --failOnCVSS 7
          --enableRetired
          --nodeAuditSkipDevDependencies 
          --disableNodeAudit
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
         name: Depcheck report
         path: ${{github.workspace}}/reports

  # dispatch:
  #   runs-on: ubuntu-latest
  #   needs: [sast, unittest]
  # Dispatch:
  #   needs: [sast, unittest]
  #   runs-on: ubuntu-latest
  #   steps:  
  #   - name: Repository Dispatch
  #     uses: peter-evans/repository-dispatch@v2

  #     with:
  #       token: ${{ secrets.REPO_ACCESS_TOKEN }}
  #       repository: bankwing/azure-java-demo-pipeline
  #       event-type: my-event
  #       client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  # call-deploy-workflow-passing-data:
  #   uses: https://github.com/bankwing/azure-java-demo-pipeline@main
  #   secrets:
  #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  #     AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}